spring.application.name=whiteboard-app

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xyhnrpwojbcpvxhmvwau
spring.datasource.password=017RIYAD@75t

spring.jpa.hibernate.ddl-auto=update
server.port=8081
