# ===================================================================
# = SERVER SETTINGS
# ===================================================================
server.port=8081

# ===================================================================
# = JPA / HIBERNATE SETTINGS
# ===================================================================

# Enable JDBC batching for improved performance
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true

# Disable Open-in-View to prevent unintended database queries and enforce best practices
spring.jpa.open-in-view=false